#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr
setxkbmap -layout de,ru -option grp:ctrl_shift_toggle

# monitors
# bspc query -M --names
# todo: monitor script
bspc monitor HDMI-A-0 -d 1 2 3 4 5
bspc monitor eDP -d 1 2 3 4 5

# key bindings
sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &

# panel
~/.config/polybar/launch.sh

# monitors
bspc monitor

# set some bsp specific
# bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap 12
bspc config border_width 2

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
